# Generated by Django 4.1.2 on 2023-03-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunger', '0005_alter_items_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='items_image',
            field=models.ImageField(default='base image.jpg', null=True, upload_to=''),
        ),
    ]
