# Generated by Django 4.1.2 on 2023-03-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunger', '0006_alter_items_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(default='vegetables-set-left-black-slate.jpg', null=True, upload_to=''),
        ),
    ]
